### ISSUE TITLE
테스트 환경 정리

### ISSUE THREAD

**Issue by jongfeel** [jdm1219/do-seung#1]
현재 프로젝트가 네트워크 통신 기반으로 되어 있다 보니
실행 환경이나 테스트 방법에 대한 문서가 있으면 좋을 것 같습니다.
작성 되면 제가 한번 해 보고 
잘 안되는 부분 있으면 피드백 드릴께요.

**Comment by jdm1219** [comment]
저번에 build해서 서버쪽에서 실행하던것에서
vue-cli proxy설정으로 build없이 :8080에서 :3000으로 넘김

1. 서버실행 (localhost:3000)
2. vue-cli실행 (localhost:8080)
3. 클라이언트에서 채팅입력 (socket.io emit으로 이벤트 서버로 전달)
4. 서버에서 채팅받음(on으로 이벤트 감지)
5. db에 입력
6. 서버에서 클라이언트로 이벤트전달(emit)
7. 클라이언트에서 이벤트 받음

하다보니까 백엔드도 하는 느낌...
일단 dynamodb연결해서 데이터까지 받아와보긴 했습니다.
저번에 말씀하실때 mysql 로컬환경으로 하려고 했는데
노트북에 깔기싫어서... dynamodb로 하겠습니다...ㅎㅎ

해야할 것
- 클라이언트 접속시 db데이터 보내줘야하는데
받아오는 시간때문에 아무것도 안나올거같음....
비동기로처리해야할듯..?
- sql 명령어찾아보기
정도일것같습니다.

**Comment by jongfeel** [comment]
테스트 방법에 대한 건 잘 적어 주셨네요.
실행 환경에 대해서도 추가로 적어주시면 좋을 것 같습니다.
예)
- 윈도우나 리눅스에서 gli clone을 한다
- node가 설치되어 있지 않으면 node를 설치한다. 현재 테스트한 노드 버전은 10.x.x 이다.
- vue-cli를 설치한다. npm install vue-cli

이런 식의 문서가 필요합니다.

즉, 이 github를 찾아온 사람이 보고 따라하면 테스트 방법대로 할 수 있게 실행 환경에 대한 설명이 필요한 거죠.

**Comment by jongfeel** [comment]
참고할 만한 문서는 github vscode 입니다.

https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

**Comment by jdm1219** [comment]
##install
```
$ git clone https://github.com/jdm1219/do-seung.git
cd \server
npm i
cd ..\vue
npm i
```
##run
terminal 두개를 사용합니다.
### server
```
cd \server
npm start
```
### vue
```
cd \vue
npm run serve
```
http://localhost:8080 로 접속합니다.

**Comment by jongfeel** [comment]
이걸 repository에 README.md 안에 적어주시면 좋습니다!

**Comment by jdm1219** [comment]
수정해서 적어놓겠습니다~

**Comment by jongfeel** [comment]
네, 왠지 제가 시켜서 한거 같은 느낌이긴 한데
그래도 잘 적어 주세요.
